// Code generated by hertz generator.

package main

import (
	"fmt"
	"log"

	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/yi-nology/zentao-release-center/internal/config"
	"github.com/yi-nology/zentao-release-center/internal/service"
	"github.com/yi-nology/zentao-release-center/internal/store"
	"github.com/yi-nology/zentao-release-center/internal/zentao"
	"github.com/yi-nology/zentao-release-center/pkg/appctx"
)

func main() {
	cfg, err := config.Load()
	if err != nil {
		log.Fatalf("load config: %v", err)
	}

	dbStore, err := store.NewStore(cfg.Database.Path)
	if err != nil {
		log.Fatalf("init store: %v", err)
	}
	defer dbStore.Close()

	zentaoClient := zentao.NewClient(cfg.ZentaoMini.BaseURL, cfg.ZentaoMini.Timeout)

	appctx.ProjectSvc = service.NewProjectService(dbStore)
	appctx.ReleaseSvc = service.NewReleaseService(dbStore, zentaoClient)
	appctx.ZentaoProxy = service.NewZentaoProxyService(zentaoClient)
	appctx.DeploymentSvc = service.NewDeploymentService(dbStore)
	appctx.ZentaoBaseURL = cfg.ZentaoMini.ZentaoBaseURL

	addr := fmt.Sprintf(":%d", cfg.Server.Port)
	h := server.Default(server.WithHostPorts(addr))

	register(h)
	h.Spin()
}
