// Code generated by hertz generator.

package center

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _healthMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _projectsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listprojectsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleteprojectMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getprojectMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _projects0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createprojectMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateprojectMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _release_itemsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listitemsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _refreshitemsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _reorderitemsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _release_items0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _additemMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _batchadditemsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleteitemMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateitemMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _release_snapshotsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listsnapshotsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getsnapshotMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _releasesMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listreleasesMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletereleaseMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getreleaseMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _exportreleaseMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _publishreleaseMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _releases0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createreleaseMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatereleaseMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _zentaoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getzentaobugsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getzentaoexecutionsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getzentaoproductsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getzentaoprojectsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getzentaotasksMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listdeploymentsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deploymentsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _adddeploymentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletedeploymentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatedeploymentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _projects1Mw() []app.HandlerFunc {
	return nil
}

func _listreposMw() []app.HandlerFunc {
	return nil
}

func _addrepoMw() []app.HandlerFunc {
	return nil
}

func _deleterepoMw() []app.HandlerFunc {
	return nil
}

func _release_branchesMw() []app.HandlerFunc {
	return nil
}

func _createreleasebranchMw() []app.HandlerFunc {
	return nil
}

func _createfeaturebranchMw() []app.HandlerFunc {
	return nil
}

func _deletebranchMw() []app.HandlerFunc {
	return nil
}

func _updatebranchMw() []app.HandlerFunc {
	return nil
}

func _listbranchesMw() []app.HandlerFunc {
	return nil
}

func _docker_imagesMw() []app.HandlerFunc {
	return nil
}

func _adddockerimageMw() []app.HandlerFunc {
	return nil
}

func _deletedockerimageMw() []app.HandlerFunc {
	return nil
}

func _listdockerimagesMw() []app.HandlerFunc {
	return nil
}

func _gitlabMw() []app.HandlerFunc {
	return nil
}

func _searchgitlabprojectsMw() []app.HandlerFunc {
	return nil
}

func _listgitlabbranchesMw() []app.HandlerFunc {
	return nil
}

func _gitlabwebhookMw() []app.HandlerFunc {
	return nil
}

func _listdockerimagepoolMw() []app.HandlerFunc {
	return nil
}

func _cibuildMw() []app.HandlerFunc {
	return nil
}

func _featuresMw() []app.HandlerFunc {
	return nil
}

func _addfeatureMw() []app.HandlerFunc {
	return nil
}

func _updatefeatureMw() []app.HandlerFunc {
	return nil
}

func _deletefeatureMw() []app.HandlerFunc {
	return nil
}

func _listfeaturesMw() []app.HandlerFunc {
	return nil
}

func _reorderfeaturesMw() []app.HandlerFunc {
	return nil
}
