// Code generated by hertz generator. DO NOT EDIT.

package center

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	center "github.com/yi-nology/zentao-release-center/biz/handler/release/center"
)

/*
 This file will register all the routes of the services in the master idl.
 And it will update automatically when you use the "update" command for the idl.
 So don't modify the contents of the file, or your code will be deleted when it is updated.
*/

// Register register routes based on the IDL 'api.${HTTP Method}' annotation.
func Register(r *server.Hertz) {

	root := r.Group("/", rootMw()...)
	{
		_api := root.Group("/api", _apiMw()...)
		_api.GET("/health", append(_healthMw(), center.Health)...)
		_api.GET("/projects", append(_listprojectsMw(), center.ListProjects)...)
		_projects := _api.Group("/projects", _projectsMw()...)
		_projects.POST("/delete", append(_deleteprojectMw(), center.DeleteProject)...)
		_projects.GET("/detail", append(_getprojectMw(), center.GetProject)...)
		_api.POST("/projects", append(_createprojectMw(), center.CreateProject)...)
		_projects0 := _api.Group("/projects", _projects0Mw()...)
		_projects0.POST("/update", append(_updateprojectMw(), center.UpdateProject)...)
		_api.GET("/release-items", append(_listitemsMw(), center.ListItems)...)
		_release_items := _api.Group("/release-items", _release_itemsMw()...)
		_release_items.POST("/refresh", append(_refreshitemsMw(), center.RefreshItems)...)
		_release_items.POST("/reorder", append(_reorderitemsMw(), center.ReorderItems)...)
		_api.POST("/release-items", append(_additemMw(), center.AddItem)...)
		_release_items0 := _api.Group("/release-items", _release_items0Mw()...)
		_release_items0.POST("/batch", append(_batchadditemsMw(), center.BatchAddItems)...)
		_release_items0.POST("/delete", append(_deleteitemMw(), center.DeleteItem)...)
		_release_items0.POST("/update", append(_updateitemMw(), center.UpdateItem)...)
		_api.GET("/release-snapshots", append(_listsnapshotsMw(), center.ListSnapshots)...)
		_release_snapshots := _api.Group("/release-snapshots", _release_snapshotsMw()...)
		_release_snapshots.GET("/detail", append(_getsnapshotMw(), center.GetSnapshot)...)
		_api.GET("/releases", append(_listreleasesMw(), center.ListReleases)...)
		_releases := _api.Group("/releases", _releasesMw()...)
		_releases.POST("/delete", append(_deletereleaseMw(), center.DeleteRelease)...)
		_releases.GET("/detail", append(_getreleaseMw(), center.GetRelease)...)
		_releases.GET("/export", append(_exportreleaseMw(), center.ExportRelease)...)
		_releases.POST("/publish", append(_publishreleaseMw(), center.PublishRelease)...)
		_api.POST("/releases", append(_createreleaseMw(), center.CreateRelease)...)
		_releases0 := _api.Group("/releases", _releases0Mw()...)
		_releases0.POST("/update", append(_updatereleaseMw(), center.UpdateRelease)...)
		{
			_zentao := _api.Group("/zentao", _zentaoMw()...)
			_zentao.GET("/bugs", append(_getzentaobugsMw(), center.GetZentaoBugs)...)
			_zentao.GET("/executions", append(_getzentaoexecutionsMw(), center.GetZentaoExecutions)...)
			_zentao.GET("/products", append(_getzentaoproductsMw(), center.GetZentaoProducts)...)
			_zentao.GET("/projects", append(_getzentaoprojectsMw(), center.GetZentaoProjects)...)
			_zentao.GET("/tasks", append(_getzentaotasksMw(), center.GetZentaoTasks)...)
		}
		{
			_projects1 := _api.Group("/projects", _projects1Mw()...)
			_projects1.GET("/repos", append(_listreposMw(), center.ListRepos)...)
			_projects1.POST("/repos", append(_addrepoMw(), center.AddRepo)...)
			_projects1.POST("/repos/delete", append(_deleterepoMw(), center.DeleteRepo)...)
		}
		{
			_release_branches := _api.Group("/release-branches", _release_branchesMw()...)
			_release_branches.POST("", append(_createreleasebranchMw(), center.CreateReleaseBranch)...)
			_release_branches.POST("/feature", append(_createfeaturebranchMw(), center.CreateFeatureBranch)...)
			_release_branches.POST("/delete", append(_deletebranchMw(), center.DeleteBranch)...)
			_release_branches.POST("/update", append(_updatebranchMw(), center.UpdateBranch)...)
			_release_branches.GET("", append(_listbranchesMw(), center.ListBranches)...)
		}
		{
			_docker_images := _api.Group("/docker-images", _docker_imagesMw()...)
			_docker_images.POST("", append(_adddockerimageMw(), center.AddDockerImage)...)
			_docker_images.POST("/delete", append(_deletedockerimageMw(), center.DeleteDockerImage)...)
			_docker_images.GET("", append(_listdockerimagesMw(), center.ListDockerImages)...)
			_docker_images.GET("/pool", append(_listdockerimagepoolMw(), center.ListDockerImagePool)...)
		}
		{
			_gitlab := _api.Group("/gitlab", _gitlabMw()...)
			_gitlab.GET("/search", append(_searchgitlabprojectsMw(), center.SearchGitlabProjects)...)
			_gitlab.GET("/branches", append(_listgitlabbranchesMw(), center.ListGitlabBranches)...)
		}
		{
			_features := _api.Group("/features", _featuresMw()...)
			_features.POST("", append(_addfeatureMw(), center.AddFeature)...)
			_features.POST("/update", append(_updatefeatureMw(), center.UpdateFeature)...)
			_features.POST("/delete", append(_deletefeatureMw(), center.DeleteFeature)...)
			_features.GET("", append(_listfeaturesMw(), center.ListFeatures)...)
			_features.POST("/reorder", append(_reorderfeaturesMw(), center.ReorderFeatures)...)
		}
		_api.POST("/webhook/gitlab", append(_gitlabwebhookMw(), center.GitlabWebhook)...)
		_api.POST("/ci/build", append(_cibuildMw(), center.CIBuild)...)
	}
}
